name: dapi
channels:
  - conda-forge
dependencies:
  - langgraph
  - langsmith
  - langchain
  - langchain-anthropic
  - langchain-google-genai
  - notebook
  - jupyter
  - jupyterlab
  - python-dotenv
  - mypy
  - ruff
  - pytest
  - openai
  - google-api-core
  - pip
  - pip:
    - deepagents
    - langgraph-api>=0.8.0
    - deepeval